name: Build and deploy app
on:
  push:
    branches: ["main"]
jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: wilsonide/fastapi-book-api:latest

      - name: Debug - Verify if image exists
        run: |
          echo "Checking image: wilsonide/fastapi-book-api:latest"
          docker pull wilsonide/fastapi-book-api:latest
          echo "Image details:"
          docker inspect wilsonide/fastapi-book-api:latest
      - name: Configure Koyeb
        uses: koyeb-community/koyeb-actions@v2
        with: 
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Deploy on Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: fastapi-book-api
          service-name: fastapi-app
          service-instance-type: free
          service-type: web
          service-routes: /:8000
          service-ports: 8000:http
          service-env: "PORT=8000"
          docker: docker.io/wilsonide/fastapi-book-api:latest